name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Surge
        run: npm install --global surge

      - name: Deploy to Surge
        run: surge ./ lisanna-firstpage.surge.sh --token ${{ secrets.SURGE_TOKEN }}

